export const PRIVACY_POLICY_TEXT = `
# Privacy Policy

Last updated: September 03, 2026

This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

We use Your Personal Data to provide and improve the Service. We collect, use, and disclose Your information as described in this Privacy Policy and, where required by applicable law, only where We have a valid legal basis to do so, including Your consent (where consent is required).

## Interpretation and Definitions

### Interpretation

The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

### Definitions

For the purposes of this Privacy Policy:

- **Account** means a unique account created for You to access Our Service or parts of Our Service.
- **Affiliate** means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
- **Company** (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to ZytroLive.
- **Cookies** are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website, among its many uses.
- **Country/State** refers to: Berlin, Germany.
- **Device** means any device that can access the Service, such as a computer, a cell phone or a digital tablet.
- **Personal Data** (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.
- **Service** refers to the Website.
- **Service Provider** means any natural or legal person who processes the data on behalf of the Company.
- **Usage Data** refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
- **User** means any individual who accesses or uses the Service.
- **Website** refers to ZytroLive.
- **You** means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.

## Collecting and Using Your Personal Information

### Types of Data Collected

#### Personal Data

While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:

- Email address

#### Usage Data

Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of Our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.

#### Tracking Technologies and Cookies

We use tracking technologies (such as cookies) to track the activity and to improve Our Service. The technologies We use may include:

- **Cookies or Browser Cookies.** A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of Our Service.
- **Web Beacons.** Certain sections of Our Service may contain small electronic files known as web beacons that permit the Company to count users who have visited those pages and for other related website statistics.

Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.

We use both Session and Persistent Cookies for the purposes set out below:

- **Necessary / Essential Cookies** (Session) — help authenticate users and prevent fraudulent use of user accounts.
- **Cookies Policy / Notice Acceptance Cookies** (Persistent) — identify whether users have accepted the use of cookies on the Website.
- **Functionality Cookies** (Persistent) — remember choices You make when You use the Website, such as Your login details or language preference.

### Use of Your Personal Data

The Company may use Personal Data for the following purposes:

- **To provide and maintain Our Service**, including to monitor the usage of Our Service.
- **To manage Your Account:** to manage Your registration as a user of the Service.
- **To contact You:** by email or other equivalent forms of electronic communication regarding updates or informative communications, including security updates.
- **To manage Your requests:** To attend and manage Your requests to Us.
- **For other purposes**: data analysis, identifying usage trends, and evaluating and improving Our Service.

We may share Your Personal Data with Service Providers (to operate the Service), for business transfers, with affiliates, with other users where You interact in public areas of the Service (such as live chat), and with Your consent.

### Retention of Your Personal Data

The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy:

- Account information: for the duration of Your Account plus up to 24 months after account closure.
- Support tickets and chat transcripts: up to 24 months.
- Usage data and server logs: up to 24 months.

### Delete Your Personal Data

You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may contact Us via the Support page to request access to, correct, or delete any Personal Data You have provided.

### Security of Your Personal Data

The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.

## Children's and Minors' Privacy

The Service is not directed to, and We do not knowingly collect Personal Information from, anyone under the age of 16. If You are a parent or guardian and You believe Your child has provided Us with Personal Information, please contact Us via the Support page.

## Links to Other Websites

Our Service may contain links to other websites that are not operated by Us. We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.

## Changes to this Privacy Policy

We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date above.

## Contact Us

If You have any questions about this Privacy Policy, please reach Us through the Support page on this site.
`;
